### ISSUE TITLE
Running Code

### ISSUE THREAD

**Issue by SolarLunix** [aodhainmcdaid/Insurance#5]
The code currently doesn't run on my PC, it constantly gives me a file not found error. Error seen below:

Class not found lyit.oscar.insurance.test.RunTest
java.lang.ClassNotFoundException: lyit.oscar.insurance.test.RunTest
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:685)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:421)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by SolarLunix** [comment]
We have found that the issue is due to the build path with the jar file for the MySQL.

**Comment by SolarLunix** [comment]
Database problem fixed along with build path, at least on Daniela's PC.
